stages:
  feature_selection:
    cmd: python .\scripts\create_feature.py
    deps:
      - .\scripts\create_feature.py
    outs:
      - .\features
  train_models:
    cmd: python scripts/train_all_models.py
    deps:
      - scripts\train_all_models.py
      - features/train_features.csv
      - features/target_sales.csv
      - features/target_customers.csv
    outs:
      - models/
